name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  ravedude:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    name: "ravedude"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install libudev
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get update && sudo apt-get install -y libudev-dev

      - name: Build ravedude
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: |
            --manifest-path ravedude/Cargo.toml
            --release
            --locked

      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ravedude-${{ matrix.os }}
          path: |
            ravedude/target/release/ravedude
            ravedude/target/release/ravedude.exe
